### ISSUE TITLE
Role installs gnome-desktop

### ISSUE THREAD

**Issue by piotrkochan** [rockandska/ansible-role-erlang#4]
This role installs gnome desktop in ubuntu server environment.

**Comment by rockandska** [comment]
Wow, since this role only install erlang from RabbitMQ, I think it will be better to open an issue on Erlang repository.

A post on [Reddit](https://www.reddit.com/r/elixir/comments/h9e8si/eslerlang_depends_on_gnomeshell/) about this issue.

Not sure if using `--no-install-recommends` will solve this.

**Comment by oyvindfo** [comment]
Maybe you should install  [erlang-nox](https://packages.debian.org/sid/erlang-nox) instead?

From the [installation guide for rabbitmq](https://www.rabbitmq.com/install-debian.html#apt-quick-start-cloudsmith) they suggest installing the following packages:

erlang-base
erlang-asn1 
erlang-crypto 
erlang-eldap 
erlang-ftp 
erlang-inets
erlang-mnesia 
erlang-os-mon 
erlang-parsetools 
erlang-public-key
erlang-runtime-tools 
erlang-snmp 
erlang-ssl
erlang-syntax-tools 
erlang-tftp 
erlang-tools 
erlang-xmerl

**Comment by rockandska** [comment]
Thanks for the advice @oyvindfo , will try to switch to erlang-nox soon since it is available in rabbitmq-erlang repositories
